FROM node:24.21-trixie AS builder

WORKDIR /app

COPY package.json ./
RUN npm install

COPY . .

ARG VITE_BASE_PATH=/
ARG VITE_API_BASE_URL
ENV VITE_BASE_PATH=$VITE_BASE_PATH
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL

RUN npm run build

FROM nginx:1.27-alpine
COPY --from=builder /app/dist /usr/share/nginx/html
